language: node_js
node_js:
  - 10.13.0
branchs:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  keep_history: true
  committer_from_gh: true
  target_branch: master
  on:
    branch: gh-pages
  github-token: $GITHUB_TOKEN
